version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "QuickBooks.Net.Tests" -c %CONFIGURATION% --version-suffix %LABEL%
- dotnet build "QuickBooks.Net.Data" -c %CONFIGURATION% --version-suffix %LABEL%
- dotnet build "QuickBooks.Net" -c %CONFIGURATION% --version-suffix %LABEL%
after_build:
- dotnet pack "QuickBooks.Net" -c %CONFIGURATION% --version-suffix %LABEL% -o artifacts
- dotnet pack "QuickBooks.Net.Data" -c %CONFIGURATION% --version-suffix %LABEL% -o artifacts
on_finish: # Run the demo to show that it works
- dotnet artifacts\ConsoleApplication\ConsoleApplication.dll
